kind = "web"
previewPath = "/"
title = "Zugzwa"
version = "1.0.0"
id = "artifacts/zugzwa"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22986

[services.development]
run = "pnpm --filter @workspace/zugzwa run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zugzwa", "run", "build" ]
publicDir = "artifacts/zugzwa/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22986"
BASE_PATH = "/"
